/*
    CeleriteQFD is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    CeleriteQFD is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with CeleriteQFD.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0

#include <stan/model/model_header.hpp>

namespace model_CeleriteQFDexN_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_CeleriteQFDexN");
    reader.add_event(296, 294, "end", "model_CeleriteQFDexN");
    return reader;
}

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__>::type>::type>::type
logLikRotation(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& t,
                   const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                   const T2__& sigma,
                   const T3__& period,
                   const T4__& Q0,
                   const T5__& dQ,
                   const T6__& f,
                   const T7__& eps,
                   const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& diag, std::ostream* pstream__);

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__>
Eigen::Matrix<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__>::type>::type>::type, Eigen::Dynamic, 1>
dotCholRotation(const Eigen::Matrix<T0__, Eigen::Dynamic, 1>& t,
                    const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& y,
                    const T2__& sigma,
                    const T3__& period,
                    const T4__& Q0,
                    const T5__& dQ,
                    const T6__& f,
                    const T7__& eps,
                    const Eigen::Matrix<T8__, Eigen::Dynamic, 1>& diag, std::ostream* pstream__);

template <typename T0__>
typename boost::math::tools::promote_args<T0__>::type
sigmoid(const T0__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 7;
        return stan::math::promote_scalar<fun_return_scalar_t__>((1 / (stan::math::exp(-(x)) + 1)));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct sigmoid_functor__ {
    template <typename T0__>
        typename boost::math::tools::promote_args<T0__>::type
    operator()(const T0__& x, std::ostream* pstream__) const {
        return sigmoid(x, pstream__);
    }
};

#include "stan_meta_header.hpp"
 class model_CeleriteQFDexN
  : public stan::model::model_base_crtp<model_CeleriteQFDexN> {
private:
        int N;
        vector_d t;
        vector_d y;
        vector_d sigma_prior;
        vector_d period_prior;
        vector_d Q0_prior;
        vector_d dQ_prior;
        vector_d f_prior;
        vector_d alpha_quiet;
        vector_d alpha_firing;
        vector_d alpha_decay;
        double mu0_quiet;
        double lambda_quiet;
        vector_d gamma_noise;
        double mu0_rate_firing;
        double sigma_rate_firing;
        double mu0_rate_decay;
        double sigma_rate_decay;
        vector_d diag;
        double eps;
public:
    model_CeleriteQFDexN(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_CeleriteQFDexN(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_CeleriteQFDexN_namespace::model_CeleriteQFDexN";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);

            current_statement_begin__ = 13;
            validate_non_negative_index("t", "N", N);
            context__.validate_dims("data initialization", "t", "vector_d", context__.to_vec(N));
            t = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("t");
            pos__ = 0;
            size_t t_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < t_j_1_max__; ++j_1__) {
                t(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 14;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(N));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 16;
            validate_non_negative_index("sigma_prior", "2", 2);
            context__.validate_dims("data initialization", "sigma_prior", "vector_d", context__.to_vec(2));
            sigma_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("sigma_prior");
            pos__ = 0;
            size_t sigma_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < sigma_prior_j_1_max__; ++j_1__) {
                sigma_prior(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 17;
            validate_non_negative_index("period_prior", "2", 2);
            context__.validate_dims("data initialization", "period_prior", "vector_d", context__.to_vec(2));
            period_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("period_prior");
            pos__ = 0;
            size_t period_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < period_prior_j_1_max__; ++j_1__) {
                period_prior(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 18;
            validate_non_negative_index("Q0_prior", "2", 2);
            context__.validate_dims("data initialization", "Q0_prior", "vector_d", context__.to_vec(2));
            Q0_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("Q0_prior");
            pos__ = 0;
            size_t Q0_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < Q0_prior_j_1_max__; ++j_1__) {
                Q0_prior(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 19;
            validate_non_negative_index("dQ_prior", "2", 2);
            context__.validate_dims("data initialization", "dQ_prior", "vector_d", context__.to_vec(2));
            dQ_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("dQ_prior");
            pos__ = 0;
            size_t dQ_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < dQ_prior_j_1_max__; ++j_1__) {
                dQ_prior(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 20;
            validate_non_negative_index("f_prior", "2", 2);
            context__.validate_dims("data initialization", "f_prior", "vector_d", context__.to_vec(2));
            f_prior = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("f_prior");
            pos__ = 0;
            size_t f_prior_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < f_prior_j_1_max__; ++j_1__) {
                f_prior(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 24;
            validate_non_negative_index("alpha_quiet", "2", 2);
            context__.validate_dims("data initialization", "alpha_quiet", "vector_d", context__.to_vec(2));
            alpha_quiet = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("alpha_quiet");
            pos__ = 0;
            size_t alpha_quiet_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < alpha_quiet_j_1_max__; ++j_1__) {
                alpha_quiet(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "alpha_quiet", alpha_quiet, 0);

            current_statement_begin__ = 26;
            validate_non_negative_index("alpha_firing", "2", 2);
            context__.validate_dims("data initialization", "alpha_firing", "vector_d", context__.to_vec(2));
            alpha_firing = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("alpha_firing");
            pos__ = 0;
            size_t alpha_firing_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < alpha_firing_j_1_max__; ++j_1__) {
                alpha_firing(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "alpha_firing", alpha_firing, 0);

            current_statement_begin__ = 28;
            validate_non_negative_index("alpha_decay", "3", 3);
            context__.validate_dims("data initialization", "alpha_decay", "vector_d", context__.to_vec(3));
            alpha_decay = Eigen::Matrix<double, Eigen::Dynamic, 1>(3);
            vals_r__ = context__.vals_r("alpha_decay");
            pos__ = 0;
            size_t alpha_decay_j_1_max__ = 3;
            for (size_t j_1__ = 0; j_1__ < alpha_decay_j_1_max__; ++j_1__) {
                alpha_decay(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "alpha_decay", alpha_decay, 0);

            current_statement_begin__ = 30;
            context__.validate_dims("data initialization", "mu0_quiet", "double", context__.to_vec());
            mu0_quiet = double(0);
            vals_r__ = context__.vals_r("mu0_quiet");
            pos__ = 0;
            mu0_quiet = vals_r__[pos__++];

            current_statement_begin__ = 31;
            context__.validate_dims("data initialization", "lambda_quiet", "double", context__.to_vec());
            lambda_quiet = double(0);
            vals_r__ = context__.vals_r("lambda_quiet");
            pos__ = 0;
            lambda_quiet = vals_r__[pos__++];

            current_statement_begin__ = 32;
            validate_non_negative_index("gamma_noise", "2", 2);
            context__.validate_dims("data initialization", "gamma_noise", "vector_d", context__.to_vec(2));
            gamma_noise = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("gamma_noise");
            pos__ = 0;
            size_t gamma_noise_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < gamma_noise_j_1_max__; ++j_1__) {
                gamma_noise(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 34;
            context__.validate_dims("data initialization", "mu0_rate_firing", "double", context__.to_vec());
            mu0_rate_firing = double(0);
            vals_r__ = context__.vals_r("mu0_rate_firing");
            pos__ = 0;
            mu0_rate_firing = vals_r__[pos__++];

            current_statement_begin__ = 35;
            context__.validate_dims("data initialization", "sigma_rate_firing", "double", context__.to_vec());
            sigma_rate_firing = double(0);
            vals_r__ = context__.vals_r("sigma_rate_firing");
            pos__ = 0;
            sigma_rate_firing = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_rate_firing", sigma_rate_firing, 0);

            current_statement_begin__ = 37;
            context__.validate_dims("data initialization", "mu0_rate_decay", "double", context__.to_vec());
            mu0_rate_decay = double(0);
            vals_r__ = context__.vals_r("mu0_rate_decay");
            pos__ = 0;
            mu0_rate_decay = vals_r__[pos__++];

            current_statement_begin__ = 38;
            context__.validate_dims("data initialization", "sigma_rate_decay", "double", context__.to_vec());
            sigma_rate_decay = double(0);
            vals_r__ = context__.vals_r("sigma_rate_decay");
            pos__ = 0;
            sigma_rate_decay = vals_r__[pos__++];
            check_greater_or_equal(function__, "sigma_rate_decay", sigma_rate_decay, 0);

            current_statement_begin__ = 40;
            validate_non_negative_index("diag", "N", N);
            context__.validate_dims("data initialization", "diag", "vector_d", context__.to_vec(N));
            diag = Eigen::Matrix<double, Eigen::Dynamic, 1>(N);
            vals_r__ = context__.vals_r("diag");
            pos__ = 0;
            size_t diag_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < diag_j_1_max__; ++j_1__) {
                diag(j_1__) = vals_r__[pos__++];
            }


            // initialize transformed data variables
            current_statement_begin__ = 44;
            eps = double(0);
            stan::math::fill(eps, DUMMY_VAR__);
            stan::math::assign(eps,1e-9);

            // execute transformed data statements

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 49;
            validate_non_negative_index("eta", "N", N);
            num_params_r__ += N;
            current_statement_begin__ = 50;
            num_params_r__ += 1;
            current_statement_begin__ = 51;
            num_params_r__ += 1;
            current_statement_begin__ = 52;
            num_params_r__ += 1;
            current_statement_begin__ = 53;
            num_params_r__ += 1;
            current_statement_begin__ = 54;
            num_params_r__ += 1;
            current_statement_begin__ = 56;
            validate_non_negative_index("theta_quiet", "2", 2);
            num_params_r__ += (2 - 1);
            current_statement_begin__ = 57;
            num_params_r__ += 1;
            current_statement_begin__ = 58;
            num_params_r__ += 1;
            current_statement_begin__ = 60;
            validate_non_negative_index("theta_firing", "2", 2);
            num_params_r__ += (2 - 1);
            current_statement_begin__ = 61;
            num_params_r__ += 1;
            current_statement_begin__ = 63;
            validate_non_negative_index("theta_decay", "3", 3);
            num_params_r__ += (3 - 1);
            current_statement_begin__ = 64;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_CeleriteQFDexN() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 49;
        if (!(context__.contains_r("eta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eta");
        pos__ = 0U;
        validate_non_negative_index("eta", "N", N);
        context__.validate_dims("parameter initialization", "eta", "vector_d", context__.to_vec(N));
        Eigen::Matrix<double, Eigen::Dynamic, 1> eta(N);
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            eta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(eta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eta: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 50;
        if (!(context__.contains_r("lsigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lsigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lsigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lsigma", "double", context__.to_vec());
        double lsigma(0);
        lsigma = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(get_base1(sigma_prior, 1, "sigma_prior", 1), get_base1(sigma_prior, 2, "sigma_prior", 1), lsigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lsigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 51;
        if (!(context__.contains_r("lperiod")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lperiod missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lperiod");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lperiod", "double", context__.to_vec());
        double lperiod(0);
        lperiod = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(get_base1(period_prior, 1, "period_prior", 1), get_base1(period_prior, 2, "period_prior", 1), lperiod);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lperiod: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 52;
        if (!(context__.contains_r("lQ0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lQ0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lQ0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lQ0", "double", context__.to_vec());
        double lQ0(0);
        lQ0 = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(get_base1(Q0_prior, 1, "Q0_prior", 1), get_base1(Q0_prior, 2, "Q0_prior", 1), lQ0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lQ0: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 53;
        if (!(context__.contains_r("ldQ")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable ldQ missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("ldQ");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "ldQ", "double", context__.to_vec());
        double ldQ(0);
        ldQ = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(get_base1(dQ_prior, 1, "dQ_prior", 1), get_base1(dQ_prior, 2, "dQ_prior", 1), ldQ);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable ldQ: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 54;
        if (!(context__.contains_r("f")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable f missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("f");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "f", "double", context__.to_vec());
        double f(0);
        f = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(get_base1(f_prior, 1, "f_prior", 1), get_base1(f_prior, 2, "f_prior", 1), f);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable f: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 56;
        if (!(context__.contains_r("theta_quiet")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_quiet missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_quiet");
        pos__ = 0U;
        validate_non_negative_index("theta_quiet", "2", 2);
        context__.validate_dims("parameter initialization", "theta_quiet", "vector_d", context__.to_vec(2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_quiet(2);
        size_t theta_quiet_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_quiet_j_1_max__; ++j_1__) {
            theta_quiet(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(theta_quiet);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_quiet: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 57;
        if (!(context__.contains_r("mu_quiet")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_quiet missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_quiet");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu_quiet", "double", context__.to_vec());
        double mu_quiet(0);
        mu_quiet = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu_quiet);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_quiet: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 58;
        if (!(context__.contains_r("sigma2_noise")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma2_noise missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma2_noise");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma2_noise", "double", context__.to_vec());
        double sigma2_noise(0);
        sigma2_noise = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma2_noise);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma2_noise: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 60;
        if (!(context__.contains_r("theta_firing")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_firing missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_firing");
        pos__ = 0U;
        validate_non_negative_index("theta_firing", "2", 2);
        context__.validate_dims("parameter initialization", "theta_firing", "vector_d", context__.to_vec(2));
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_firing(2);
        size_t theta_firing_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_firing_j_1_max__; ++j_1__) {
            theta_firing(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(theta_firing);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_firing: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 61;
        if (!(context__.contains_r("lograte_firing")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lograte_firing missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lograte_firing");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "lograte_firing", "double", context__.to_vec());
        double lograte_firing(0);
        lograte_firing = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(lograte_firing);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lograte_firing: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 63;
        if (!(context__.contains_r("theta_decay")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_decay missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_decay");
        pos__ = 0U;
        validate_non_negative_index("theta_decay", "3", 3);
        context__.validate_dims("parameter initialization", "theta_decay", "vector_d", context__.to_vec(3));
        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_decay(3);
        size_t theta_decay_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < theta_decay_j_1_max__; ++j_1__) {
            theta_decay(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(theta_decay);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_decay: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 64;
        if (!(context__.contains_r("logitrate_decay")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable logitrate_decay missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("logitrate_decay");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "logitrate_decay", "double", context__.to_vec());
        double logitrate_decay(0);
        logitrate_decay = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(logitrate_decay);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable logitrate_decay: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 49;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> eta;
            (void) eta;  // dummy to suppress unused var warning
            if (jacobian__)
                eta = in__.vector_constrain(N, lp__);
            else
                eta = in__.vector_constrain(N);

            current_statement_begin__ = 50;
            local_scalar_t__ lsigma;
            (void) lsigma;  // dummy to suppress unused var warning
            if (jacobian__)
                lsigma = in__.scalar_lub_constrain(get_base1(sigma_prior, 1, "sigma_prior", 1), get_base1(sigma_prior, 2, "sigma_prior", 1), lp__);
            else
                lsigma = in__.scalar_lub_constrain(get_base1(sigma_prior, 1, "sigma_prior", 1), get_base1(sigma_prior, 2, "sigma_prior", 1));

            current_statement_begin__ = 51;
            local_scalar_t__ lperiod;
            (void) lperiod;  // dummy to suppress unused var warning
            if (jacobian__)
                lperiod = in__.scalar_lub_constrain(get_base1(period_prior, 1, "period_prior", 1), get_base1(period_prior, 2, "period_prior", 1), lp__);
            else
                lperiod = in__.scalar_lub_constrain(get_base1(period_prior, 1, "period_prior", 1), get_base1(period_prior, 2, "period_prior", 1));

            current_statement_begin__ = 52;
            local_scalar_t__ lQ0;
            (void) lQ0;  // dummy to suppress unused var warning
            if (jacobian__)
                lQ0 = in__.scalar_lub_constrain(get_base1(Q0_prior, 1, "Q0_prior", 1), get_base1(Q0_prior, 2, "Q0_prior", 1), lp__);
            else
                lQ0 = in__.scalar_lub_constrain(get_base1(Q0_prior, 1, "Q0_prior", 1), get_base1(Q0_prior, 2, "Q0_prior", 1));

            current_statement_begin__ = 53;
            local_scalar_t__ ldQ;
            (void) ldQ;  // dummy to suppress unused var warning
            if (jacobian__)
                ldQ = in__.scalar_lub_constrain(get_base1(dQ_prior, 1, "dQ_prior", 1), get_base1(dQ_prior, 2, "dQ_prior", 1), lp__);
            else
                ldQ = in__.scalar_lub_constrain(get_base1(dQ_prior, 1, "dQ_prior", 1), get_base1(dQ_prior, 2, "dQ_prior", 1));

            current_statement_begin__ = 54;
            local_scalar_t__ f;
            (void) f;  // dummy to suppress unused var warning
            if (jacobian__)
                f = in__.scalar_lub_constrain(get_base1(f_prior, 1, "f_prior", 1), get_base1(f_prior, 2, "f_prior", 1), lp__);
            else
                f = in__.scalar_lub_constrain(get_base1(f_prior, 1, "f_prior", 1), get_base1(f_prior, 2, "f_prior", 1));

            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_quiet;
            (void) theta_quiet;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_quiet = in__.simplex_constrain(2, lp__);
            else
                theta_quiet = in__.simplex_constrain(2);

            current_statement_begin__ = 57;
            local_scalar_t__ mu_quiet;
            (void) mu_quiet;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_quiet = in__.scalar_constrain(lp__);
            else
                mu_quiet = in__.scalar_constrain();

            current_statement_begin__ = 58;
            local_scalar_t__ sigma2_noise;
            (void) sigma2_noise;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma2_noise = in__.scalar_lb_constrain(0, lp__);
            else
                sigma2_noise = in__.scalar_lb_constrain(0);

            current_statement_begin__ = 60;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_firing;
            (void) theta_firing;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_firing = in__.simplex_constrain(2, lp__);
            else
                theta_firing = in__.simplex_constrain(2);

            current_statement_begin__ = 61;
            local_scalar_t__ lograte_firing;
            (void) lograte_firing;  // dummy to suppress unused var warning
            if (jacobian__)
                lograte_firing = in__.scalar_constrain(lp__);
            else
                lograte_firing = in__.scalar_constrain();

            current_statement_begin__ = 63;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> theta_decay;
            (void) theta_decay;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_decay = in__.simplex_constrain(3, lp__);
            else
                theta_decay = in__.simplex_constrain(3);

            current_statement_begin__ = 64;
            local_scalar_t__ logitrate_decay;
            (void) logitrate_decay;  // dummy to suppress unused var warning
            if (jacobian__)
                logitrate_decay = in__.scalar_constrain(lp__);
            else
                logitrate_decay = in__.scalar_constrain();

            // transformed parameters
            current_statement_begin__ = 68;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);

            current_statement_begin__ = 69;
            local_scalar_t__ period;
            (void) period;  // dummy to suppress unused var warning
            stan::math::initialize(period, DUMMY_VAR__);
            stan::math::fill(period, DUMMY_VAR__);

            current_statement_begin__ = 70;
            local_scalar_t__ Q0;
            (void) Q0;  // dummy to suppress unused var warning
            stan::math::initialize(Q0, DUMMY_VAR__);
            stan::math::fill(Q0, DUMMY_VAR__);

            current_statement_begin__ = 71;
            local_scalar_t__ dQ;
            (void) dQ;  // dummy to suppress unused var warning
            stan::math::initialize(dQ, DUMMY_VAR__);
            stan::math::fill(dQ, DUMMY_VAR__);

            current_statement_begin__ = 72;
            local_scalar_t__ rate_firing;
            (void) rate_firing;  // dummy to suppress unused var warning
            stan::math::initialize(rate_firing, DUMMY_VAR__);
            stan::math::fill(rate_firing, DUMMY_VAR__);

            current_statement_begin__ = 73;
            local_scalar_t__ rate_decay;
            (void) rate_decay;  // dummy to suppress unused var warning
            stan::math::initialize(rate_decay, DUMMY_VAR__);
            stan::math::fill(rate_decay, DUMMY_VAR__);

            // transformed parameters block statements
            current_statement_begin__ = 74;
            stan::math::assign(sigma, stan::math::exp(lsigma));
            current_statement_begin__ = 75;
            stan::math::assign(period, stan::math::exp(lperiod));
            current_statement_begin__ = 76;
            stan::math::assign(Q0, stan::math::exp(lQ0));
            current_statement_begin__ = 77;
            stan::math::assign(dQ, stan::math::exp(ldQ));
            current_statement_begin__ = 78;
            stan::math::assign(rate_firing, stan::math::exp(lograte_firing));
            current_statement_begin__ = 79;
            stan::math::assign(rate_decay, sigmoid(logitrate_decay, pstream__));

            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 68;
            if (stan::math::is_uninitialized(sigma)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: sigma";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable sigma: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 69;
            if (stan::math::is_uninitialized(period)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: period";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable period: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 70;
            if (stan::math::is_uninitialized(Q0)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: Q0";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable Q0: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 71;
            if (stan::math::is_uninitialized(dQ)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: dQ";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable dQ: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 72;
            if (stan::math::is_uninitialized(rate_firing)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: rate_firing";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable rate_firing: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            current_statement_begin__ = 73;
            if (stan::math::is_uninitialized(rate_decay)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: rate_decay";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable rate_decay: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }

            // model body
            {
            current_statement_begin__ = 83;
            validate_non_negative_index("trend", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> trend(N);
            stan::math::initialize(trend, DUMMY_VAR__);
            stan::math::fill(trend, DUMMY_VAR__);

            current_statement_begin__ = 84;
            validate_non_negative_index("yd", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> yd(N);
            stan::math::initialize(yd, DUMMY_VAR__);
            stan::math::fill(yd, DUMMY_VAR__);

            current_statement_begin__ = 85;
            validate_non_negative_index("accu_quiet", "2", 2);
            std::vector<local_scalar_t__  > accu_quiet(2, local_scalar_t__(DUMMY_VAR__));
            stan::math::initialize(accu_quiet, DUMMY_VAR__);
            stan::math::fill(accu_quiet, DUMMY_VAR__);

            current_statement_begin__ = 86;
            validate_non_negative_index("accu_firing", "3", 3);
            std::vector<local_scalar_t__  > accu_firing(3, local_scalar_t__(DUMMY_VAR__));
            stan::math::initialize(accu_firing, DUMMY_VAR__);
            stan::math::fill(accu_firing, DUMMY_VAR__);

            current_statement_begin__ = 87;
            validate_non_negative_index("accu_decay", "2", 2);
            std::vector<local_scalar_t__  > accu_decay(2, local_scalar_t__(DUMMY_VAR__));
            stan::math::initialize(accu_decay, DUMMY_VAR__);
            stan::math::fill(accu_decay, DUMMY_VAR__);

            current_statement_begin__ = 88;
            validate_non_negative_index("gamma", "(N - 1)", (N - 1));
            validate_non_negative_index("gamma", "3", 3);
            std::vector<std::vector<local_scalar_t__  >  > gamma((N - 1), std::vector<local_scalar_t__>(3, local_scalar_t__(DUMMY_VAR__)));
            stan::math::initialize(gamma, DUMMY_VAR__);
            stan::math::fill(gamma, DUMMY_VAR__);


            current_statement_begin__ = 90;
            stan::math::assign(trend, dotCholRotation(t, eta, sigma, period, Q0, dQ, f, eps, diag, pstream__));
            current_statement_begin__ = 92;
            lp_accum__.add(normal_log<propto__>(eta, 0, 1));
            current_statement_begin__ = 97;
            lp_accum__.add(inv_gamma_log<propto__>(sigma2_noise, get_base1(gamma_noise, 1, "gamma_noise", 1), get_base1(gamma_noise, 2, "gamma_noise", 1)));
            current_statement_begin__ = 99;
            lp_accum__.add(normal_log<propto__>(mu_quiet, mu0_quiet, stan::math::sqrt((sigma2_noise / lambda_quiet))));
            current_statement_begin__ = 102;
            lp_accum__.add(normal_log<propto__>(lograte_firing, mu0_rate_firing, sigma_rate_firing));
            current_statement_begin__ = 103;
            lp_accum__.add(normal_log<propto__>(logitrate_decay, mu0_rate_decay, sigma_rate_decay));
            current_statement_begin__ = 105;
            lp_accum__.add(dirichlet_log<propto__>(theta_quiet, alpha_quiet));
            current_statement_begin__ = 106;
            lp_accum__.add(dirichlet_log<propto__>(theta_firing, alpha_firing));
            current_statement_begin__ = 107;
            lp_accum__.add(dirichlet_log<propto__>(theta_decay, alpha_decay));
            current_statement_begin__ = 112;
            stan::math::assign(yd, subtract(subtract(y, trend), mu_quiet));
            current_statement_begin__ = 119;
            stan::model::assign(gamma, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        normal_log(get_base1(yd, 2, "yd", 1), 0, stan::math::sqrt(sigma2_noise)), 
                        "assigning variable gamma");
            current_statement_begin__ = 121;
            stan::model::assign(gamma, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                        exp_mod_normal_log(get_base1(yd, 2, "yd", 1), get_base1(yd, 1, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing), 
                        "assigning variable gamma");
            current_statement_begin__ = 123;
            stan::model::assign(gamma, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                        normal_log(get_base1(yd, 2, "yd", 1), (rate_decay * get_base1(yd, 1, "yd", 1)), stan::math::sqrt(sigma2_noise)), 
                        "assigning variable gamma");
            current_statement_begin__ = 126;
            for (int tt = 2; tt <= (N - 1); ++tt) {

                current_statement_begin__ = 129;
                stan::model::assign(accu_quiet, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 1, "gamma", 2) + stan::math::log(get_base1(theta_quiet, 1, "theta_quiet", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), 0, stan::math::sqrt(sigma2_noise))), 
                            "assigning variable accu_quiet");
                current_statement_begin__ = 132;
                stan::model::assign(accu_quiet, 
                            stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 3, "gamma", 2) + stan::math::log(get_base1(theta_decay, 1, "theta_decay", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), 0, stan::math::sqrt(sigma2_noise))), 
                            "assigning variable accu_quiet");
                current_statement_begin__ = 135;
                stan::model::assign(gamma, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            log_sum_exp(accu_quiet), 
                            "assigning variable gamma");
                current_statement_begin__ = 139;
                stan::model::assign(accu_firing, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 1, "gamma", 2) + stan::math::log(get_base1(theta_quiet, 2, "theta_quiet", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)), 
                            "assigning variable accu_firing");
                current_statement_begin__ = 142;
                stan::model::assign(accu_firing, 
                            stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 2, "gamma", 2) + stan::math::log(get_base1(theta_firing, 1, "theta_firing", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)), 
                            "assigning variable accu_firing");
                current_statement_begin__ = 145;
                stan::model::assign(accu_firing, 
                            stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 3, "gamma", 2) + stan::math::log(get_base1(theta_decay, 2, "theta_decay", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)), 
                            "assigning variable accu_firing");
                current_statement_begin__ = 147;
                stan::model::assign(gamma, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                            log_sum_exp(accu_firing), 
                            "assigning variable gamma");
                current_statement_begin__ = 151;
                stan::model::assign(accu_decay, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 2, "gamma", 2) + stan::math::log(get_base1(theta_firing, 2, "theta_firing", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), (rate_decay * get_base1(yd, tt, "yd", 1)), stan::math::sqrt(sigma2_noise))), 
                            "assigning variable accu_decay");
                current_statement_begin__ = 154;
                stan::model::assign(accu_decay, 
                            stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                            ((get_base1(get_base1(gamma, (tt - 1), "gamma", 1), 3, "gamma", 2) + stan::math::log(get_base1(theta_decay, 3, "theta_decay", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), (rate_decay * get_base1(yd, tt, "yd", 1)), stan::math::sqrt(sigma2_noise))), 
                            "assigning variable accu_decay");
                current_statement_begin__ = 156;
                stan::model::assign(gamma, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                            log_sum_exp(accu_decay), 
                            "assigning variable gamma");
            }
            current_statement_begin__ = 159;
            lp_accum__.add(log_sum_exp(get_base1(gamma, (N - 1), "gamma", 1)));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("eta");
        names__.push_back("lsigma");
        names__.push_back("lperiod");
        names__.push_back("lQ0");
        names__.push_back("ldQ");
        names__.push_back("f");
        names__.push_back("theta_quiet");
        names__.push_back("mu_quiet");
        names__.push_back("sigma2_noise");
        names__.push_back("theta_firing");
        names__.push_back("lograte_firing");
        names__.push_back("theta_decay");
        names__.push_back("logitrate_decay");
        names__.push_back("sigma");
        names__.push_back("period");
        names__.push_back("Q0");
        names__.push_back("dQ");
        names__.push_back("rate_firing");
        names__.push_back("rate_decay");
        names__.push_back("viterbi");
        names__.push_back("trend");
        names__.push_back("log_p_state");
        names__.push_back("Q1");
        names__.push_back("w1");
        names__.push_back("S1");
        names__.push_back("Q2");
        names__.push_back("w2");
        names__.push_back("S2");
        names__.push_back("sigma1");
        names__.push_back("rho1");
        names__.push_back("tau1");
        names__.push_back("sigma2");
        names__.push_back("rho2");
        names__.push_back("tau2");
        names__.push_back("amp");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(2);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((N - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_CeleriteQFDexN_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> eta = in__.vector_constrain(N);
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            vars__.push_back(eta(j_1__));
        }

        double lsigma = in__.scalar_lub_constrain(get_base1(sigma_prior, 1, "sigma_prior", 1), get_base1(sigma_prior, 2, "sigma_prior", 1));
        vars__.push_back(lsigma);

        double lperiod = in__.scalar_lub_constrain(get_base1(period_prior, 1, "period_prior", 1), get_base1(period_prior, 2, "period_prior", 1));
        vars__.push_back(lperiod);

        double lQ0 = in__.scalar_lub_constrain(get_base1(Q0_prior, 1, "Q0_prior", 1), get_base1(Q0_prior, 2, "Q0_prior", 1));
        vars__.push_back(lQ0);

        double ldQ = in__.scalar_lub_constrain(get_base1(dQ_prior, 1, "dQ_prior", 1), get_base1(dQ_prior, 2, "dQ_prior", 1));
        vars__.push_back(ldQ);

        double f = in__.scalar_lub_constrain(get_base1(f_prior, 1, "f_prior", 1), get_base1(f_prior, 2, "f_prior", 1));
        vars__.push_back(f);

        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_quiet = in__.simplex_constrain(2);
        size_t theta_quiet_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_quiet_j_1_max__; ++j_1__) {
            vars__.push_back(theta_quiet(j_1__));
        }

        double mu_quiet = in__.scalar_constrain();
        vars__.push_back(mu_quiet);

        double sigma2_noise = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma2_noise);

        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_firing = in__.simplex_constrain(2);
        size_t theta_firing_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_firing_j_1_max__; ++j_1__) {
            vars__.push_back(theta_firing(j_1__));
        }

        double lograte_firing = in__.scalar_constrain();
        vars__.push_back(lograte_firing);

        Eigen::Matrix<double, Eigen::Dynamic, 1> theta_decay = in__.simplex_constrain(3);
        size_t theta_decay_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < theta_decay_j_1_max__; ++j_1__) {
            vars__.push_back(theta_decay(j_1__));
        }

        double logitrate_decay = in__.scalar_constrain();
        vars__.push_back(logitrate_decay);

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            // declare and define transformed parameters
            current_statement_begin__ = 68;
            double sigma;
            (void) sigma;  // dummy to suppress unused var warning
            stan::math::initialize(sigma, DUMMY_VAR__);
            stan::math::fill(sigma, DUMMY_VAR__);

            current_statement_begin__ = 69;
            double period;
            (void) period;  // dummy to suppress unused var warning
            stan::math::initialize(period, DUMMY_VAR__);
            stan::math::fill(period, DUMMY_VAR__);

            current_statement_begin__ = 70;
            double Q0;
            (void) Q0;  // dummy to suppress unused var warning
            stan::math::initialize(Q0, DUMMY_VAR__);
            stan::math::fill(Q0, DUMMY_VAR__);

            current_statement_begin__ = 71;
            double dQ;
            (void) dQ;  // dummy to suppress unused var warning
            stan::math::initialize(dQ, DUMMY_VAR__);
            stan::math::fill(dQ, DUMMY_VAR__);

            current_statement_begin__ = 72;
            double rate_firing;
            (void) rate_firing;  // dummy to suppress unused var warning
            stan::math::initialize(rate_firing, DUMMY_VAR__);
            stan::math::fill(rate_firing, DUMMY_VAR__);

            current_statement_begin__ = 73;
            double rate_decay;
            (void) rate_decay;  // dummy to suppress unused var warning
            stan::math::initialize(rate_decay, DUMMY_VAR__);
            stan::math::fill(rate_decay, DUMMY_VAR__);

            // do transformed parameters statements
            current_statement_begin__ = 74;
            stan::math::assign(sigma, stan::math::exp(lsigma));
            current_statement_begin__ = 75;
            stan::math::assign(period, stan::math::exp(lperiod));
            current_statement_begin__ = 76;
            stan::math::assign(Q0, stan::math::exp(lQ0));
            current_statement_begin__ = 77;
            stan::math::assign(dQ, stan::math::exp(ldQ));
            current_statement_begin__ = 78;
            stan::math::assign(rate_firing, stan::math::exp(lograte_firing));
            current_statement_begin__ = 79;
            stan::math::assign(rate_decay, sigmoid(logitrate_decay, pstream__));

            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // write transformed parameters
            if (include_tparams__) {
                vars__.push_back(sigma);
                vars__.push_back(period);
                vars__.push_back(Q0);
                vars__.push_back(dQ);
                vars__.push_back(rate_firing);
                vars__.push_back(rate_decay);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 163;
            validate_non_negative_index("viterbi", "(N - 1)", (N - 1));
            std::vector<int> viterbi((N - 1), int(0));
            stan::math::fill(viterbi, std::numeric_limits<int>::min());

            current_statement_begin__ = 164;
            validate_non_negative_index("trend", "N", N);
            Eigen::Matrix<double, Eigen::Dynamic, 1> trend(N);
            stan::math::initialize(trend, DUMMY_VAR__);
            stan::math::fill(trend, DUMMY_VAR__);

            current_statement_begin__ = 165;
            double log_p_state;
            (void) log_p_state;  // dummy to suppress unused var warning
            stan::math::initialize(log_p_state, DUMMY_VAR__);
            stan::math::fill(log_p_state, DUMMY_VAR__);

            current_statement_begin__ = 166;
            double Q1;
            (void) Q1;  // dummy to suppress unused var warning
            stan::math::initialize(Q1, DUMMY_VAR__);
            stan::math::fill(Q1, DUMMY_VAR__);

            current_statement_begin__ = 167;
            double w1;
            (void) w1;  // dummy to suppress unused var warning
            stan::math::initialize(w1, DUMMY_VAR__);
            stan::math::fill(w1, DUMMY_VAR__);

            current_statement_begin__ = 168;
            double S1;
            (void) S1;  // dummy to suppress unused var warning
            stan::math::initialize(S1, DUMMY_VAR__);
            stan::math::fill(S1, DUMMY_VAR__);

            current_statement_begin__ = 169;
            double Q2;
            (void) Q2;  // dummy to suppress unused var warning
            stan::math::initialize(Q2, DUMMY_VAR__);
            stan::math::fill(Q2, DUMMY_VAR__);

            current_statement_begin__ = 170;
            double w2;
            (void) w2;  // dummy to suppress unused var warning
            stan::math::initialize(w2, DUMMY_VAR__);
            stan::math::fill(w2, DUMMY_VAR__);

            current_statement_begin__ = 171;
            double S2;
            (void) S2;  // dummy to suppress unused var warning
            stan::math::initialize(S2, DUMMY_VAR__);
            stan::math::fill(S2, DUMMY_VAR__);

            current_statement_begin__ = 173;
            double sigma1;
            (void) sigma1;  // dummy to suppress unused var warning
            stan::math::initialize(sigma1, DUMMY_VAR__);
            stan::math::fill(sigma1, DUMMY_VAR__);

            current_statement_begin__ = 174;
            double rho1;
            (void) rho1;  // dummy to suppress unused var warning
            stan::math::initialize(rho1, DUMMY_VAR__);
            stan::math::fill(rho1, DUMMY_VAR__);

            current_statement_begin__ = 175;
            double tau1;
            (void) tau1;  // dummy to suppress unused var warning
            stan::math::initialize(tau1, DUMMY_VAR__);
            stan::math::fill(tau1, DUMMY_VAR__);

            current_statement_begin__ = 177;
            double sigma2;
            (void) sigma2;  // dummy to suppress unused var warning
            stan::math::initialize(sigma2, DUMMY_VAR__);
            stan::math::fill(sigma2, DUMMY_VAR__);

            current_statement_begin__ = 178;
            double rho2;
            (void) rho2;  // dummy to suppress unused var warning
            stan::math::initialize(rho2, DUMMY_VAR__);
            stan::math::fill(rho2, DUMMY_VAR__);

            current_statement_begin__ = 179;
            double tau2;
            (void) tau2;  // dummy to suppress unused var warning
            stan::math::initialize(tau2, DUMMY_VAR__);
            stan::math::fill(tau2, DUMMY_VAR__);

            current_statement_begin__ = 181;
            double amp;
            (void) amp;  // dummy to suppress unused var warning
            stan::math::initialize(amp, DUMMY_VAR__);
            stan::math::fill(amp, DUMMY_VAR__);

            // generated quantities statements
            current_statement_begin__ = 183;
            stan::math::assign(amp, ((sigma * sigma) / (1 + f)));
            current_statement_begin__ = 184;
            stan::math::assign(Q1, ((0.5 + Q0) + dQ));
            current_statement_begin__ = 185;
            stan::math::assign(w1, (((4 * 3.1415926) * Q1) / (period * stan::math::sqrt((((4 * Q1) * Q1) - 1)))));
            current_statement_begin__ = 186;
            stan::math::assign(S1, (amp / (w1 * Q1)));
            current_statement_begin__ = 187;
            stan::math::assign(Q2, (0.5 + Q0));
            current_statement_begin__ = 188;
            stan::math::assign(w2, (((8 * 3.1415926) * Q2) / (period * stan::math::sqrt((((4 * Q2) * Q2) - 1)))));
            current_statement_begin__ = 189;
            stan::math::assign(S2, ((f * amp) / (w2 * Q2)));
            current_statement_begin__ = 191;
            stan::math::assign(rho1, ((2 * 3.1415926) / w1));
            current_statement_begin__ = 192;
            stan::math::assign(rho2, ((2 * 3.1415926) / w2));
            current_statement_begin__ = 193;
            stan::math::assign(tau1, ((2 * Q1) / w1));
            current_statement_begin__ = 194;
            stan::math::assign(tau2, ((2 * Q2) / w2));
            current_statement_begin__ = 195;
            stan::math::assign(sigma1, stan::math::sqrt(((S1 * w1) * Q1)));
            current_statement_begin__ = 196;
            stan::math::assign(sigma2, stan::math::sqrt(((S2 * w2) * Q2)));
            {
            current_statement_begin__ = 199;
            validate_non_negative_index("back_ptr", "(N - 1)", (N - 1));
            validate_non_negative_index("back_ptr", "3", 3);
            std::vector<std::vector<int  >  > back_ptr((N - 1), std::vector<int>(3, int(0)));
            stan::math::fill(back_ptr, std::numeric_limits<int>::min());

            current_statement_begin__ = 200;
            validate_non_negative_index("best_logp", "(N - 1)", (N - 1));
            validate_non_negative_index("best_logp", "3", 3);
            std::vector<std::vector<local_scalar_t__  >  > best_logp((N - 1), std::vector<local_scalar_t__>(3, local_scalar_t__(DUMMY_VAR__)));
            stan::math::initialize(best_logp, DUMMY_VAR__);
            stan::math::fill(best_logp, DUMMY_VAR__);

            current_statement_begin__ = 201;
            local_scalar_t__ best_total_logp(DUMMY_VAR__);
            (void) best_total_logp;  // dummy to suppress unused var warning
            stan::math::initialize(best_total_logp, DUMMY_VAR__);
            stan::math::fill(best_total_logp, DUMMY_VAR__);

            current_statement_begin__ = 202;
            local_scalar_t__ logp(DUMMY_VAR__);
            (void) logp;  // dummy to suppress unused var warning
            stan::math::initialize(logp, DUMMY_VAR__);
            stan::math::fill(logp, DUMMY_VAR__);

            current_statement_begin__ = 203;
            validate_non_negative_index("yd", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> yd(N);
            stan::math::initialize(yd, DUMMY_VAR__);
            stan::math::fill(yd, DUMMY_VAR__);


            current_statement_begin__ = 204;
            stan::math::assign(trend, dotCholRotation(t, eta, sigma, period, Q0, dQ, f, eps, diag, pstream__));
            current_statement_begin__ = 206;
            stan::math::assign(yd, subtract(subtract(y, trend), mu_quiet));
            current_statement_begin__ = 209;
            stan::model::assign(best_logp, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                        normal_log(get_base1(yd, 2, "yd", 1), 0, stan::math::sqrt(sigma2_noise)), 
                        "assigning variable best_logp");
            current_statement_begin__ = 211;
            stan::model::assign(best_logp, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                        exp_mod_normal_log(get_base1(yd, 2, "yd", 1), get_base1(yd, 1, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing), 
                        "assigning variable best_logp");
            current_statement_begin__ = 213;
            stan::model::assign(best_logp, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                        normal_log(get_base1(yd, 2, "yd", 1), (rate_decay * get_base1(yd, 1, "yd", 1)), stan::math::sqrt(sigma2_noise)), 
                        "assigning variable best_logp");
            current_statement_begin__ = 215;
            for (int tt = 2; tt <= (N - 1); ++tt) {

                current_statement_begin__ = 217;
                stan::model::assign(best_logp, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                            stan::math::negative_infinity(), 
                            "assigning variable best_logp");
                current_statement_begin__ = 219;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 1, "best_logp", 2) + stan::math::log(get_base1(theta_quiet, 1, "theta_quiet", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), 0, stan::math::sqrt(sigma2_noise))));
                current_statement_begin__ = 221;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 1, "best_logp", 2)))) {

                    current_statement_begin__ = 222;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                1, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 223;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 227;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 3, "best_logp", 2) + stan::math::log(get_base1(theta_decay, 1, "theta_decay", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), 0, stan::math::sqrt(sigma2_noise))));
                current_statement_begin__ = 229;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 1, "best_logp", 2)))) {

                    current_statement_begin__ = 230;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                3, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 231;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 235;
                stan::model::assign(best_logp, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                            stan::math::negative_infinity(), 
                            "assigning variable best_logp");
                current_statement_begin__ = 237;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 1, "best_logp", 2) + stan::math::log(get_base1(theta_quiet, 2, "theta_quiet", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)));
                current_statement_begin__ = 239;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 2, "best_logp", 2)))) {

                    current_statement_begin__ = 240;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                1, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 241;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 244;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 2, "best_logp", 2) + stan::math::log(get_base1(theta_firing, 1, "theta_firing", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)));
                current_statement_begin__ = 247;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 2, "best_logp", 2)))) {

                    current_statement_begin__ = 248;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                2, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 249;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 252;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 3, "best_logp", 2) + stan::math::log(get_base1(theta_decay, 2, "theta_decay", 1))) + exp_mod_normal_log(get_base1(yd, (tt + 1), "yd", 1), get_base1(yd, tt, "yd", 1), stan::math::sqrt(sigma2_noise), rate_firing)));
                current_statement_begin__ = 255;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 2, "best_logp", 2)))) {

                    current_statement_begin__ = 256;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                3, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 257;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 261;
                stan::model::assign(best_logp, 
                            stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                            stan::math::negative_infinity(), 
                            "assigning variable best_logp");
                current_statement_begin__ = 264;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 2, "best_logp", 2) + stan::math::log(get_base1(theta_firing, 2, "theta_firing", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), (rate_decay * get_base1(yd, tt, "yd", 1)), stan::math::sqrt(sigma2_noise))));
                current_statement_begin__ = 267;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 3, "best_logp", 2)))) {

                    current_statement_begin__ = 268;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                2, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 269;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
                current_statement_begin__ = 273;
                stan::math::assign(logp, ((get_base1(get_base1(best_logp, (tt - 1), "best_logp", 1), 3, "best_logp", 2) + stan::math::log(get_base1(theta_decay, 3, "theta_decay", 1))) + normal_log(get_base1(yd, (tt + 1), "yd", 1), (rate_decay * get_base1(yd, tt, "yd", 1)), stan::math::sqrt(sigma2_noise))));
                current_statement_begin__ = 275;
                if (as_bool(logical_gt(logp, get_base1(get_base1(best_logp, tt, "best_logp", 1), 3, "best_logp", 2)))) {

                    current_statement_begin__ = 276;
                    stan::model::assign(back_ptr, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                3, 
                                "assigning variable back_ptr");
                    current_statement_begin__ = 277;
                    stan::model::assign(best_logp, 
                                stan::model::cons_list(stan::model::index_uni(tt), stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list())), 
                                logp, 
                                "assigning variable best_logp");
                }
            }
            current_statement_begin__ = 282;
            stan::math::assign(log_p_state, max(get_base1(best_logp, (N - 1), "best_logp", 1)));
            current_statement_begin__ = 283;
            for (int i = 1; i <= 3; ++i) {

                current_statement_begin__ = 284;
                if (as_bool(logical_eq(get_base1(get_base1(best_logp, (N - 1), "best_logp", 1), i, "best_logp", 2), log_p_state))) {

                    current_statement_begin__ = 285;
                    stan::model::assign(viterbi, 
                                stan::model::cons_list(stan::model::index_uni((N - 1)), stan::model::nil_index_list()), 
                                i, 
                                "assigning variable viterbi");
                }
            }
            current_statement_begin__ = 289;
            for (int tt = 2; tt <= (N - 1); ++tt) {

                current_statement_begin__ = 290;
                stan::model::assign(viterbi, 
                            stan::model::cons_list(stan::model::index_uni((N - tt)), stan::model::nil_index_list()), 
                            get_base1(get_base1(back_ptr, ((N - tt) + 1), "back_ptr", 1), get_base1(viterbi, ((N - tt) + 1), "viterbi", 1), "back_ptr", 2), 
                            "assigning variable viterbi");
            }
            }

            // validate, write generated quantities
            current_statement_begin__ = 163;
            size_t viterbi_i_0_max__ = (N - 1);
            for (size_t i_0__ = 0; i_0__ < viterbi_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "viterbi[i_0__]", viterbi[i_0__], 1);
                check_less_or_equal(function__, "viterbi[i_0__]", viterbi[i_0__], 3);
            }

            size_t viterbi_k_0_max__ = (N - 1);
            for (size_t k_0__ = 0; k_0__ < viterbi_k_0_max__; ++k_0__) {
                vars__.push_back(viterbi[k_0__]);
            }

            current_statement_begin__ = 164;
            size_t trend_j_1_max__ = N;
            for (size_t j_1__ = 0; j_1__ < trend_j_1_max__; ++j_1__) {
                vars__.push_back(trend(j_1__));
            }

            current_statement_begin__ = 165;
            vars__.push_back(log_p_state);

            current_statement_begin__ = 166;
            vars__.push_back(Q1);

            current_statement_begin__ = 167;
            vars__.push_back(w1);

            current_statement_begin__ = 168;
            vars__.push_back(S1);

            current_statement_begin__ = 169;
            vars__.push_back(Q2);

            current_statement_begin__ = 170;
            vars__.push_back(w2);

            current_statement_begin__ = 171;
            vars__.push_back(S2);

            current_statement_begin__ = 173;
            vars__.push_back(sigma1);

            current_statement_begin__ = 174;
            vars__.push_back(rho1);

            current_statement_begin__ = 175;
            vars__.push_back(tau1);

            current_statement_begin__ = 177;
            vars__.push_back(sigma2);

            current_statement_begin__ = 178;
            vars__.push_back(rho2);

            current_statement_begin__ = 179;
            vars__.push_back(tau2);

            current_statement_begin__ = 181;
            vars__.push_back(amp);

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    std::string model_name() const {
        return "model_CeleriteQFDexN";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lsigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lperiod";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lQ0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ldQ";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "f";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_quiet_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_quiet_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_quiet" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_quiet";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2_noise";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_firing_j_1_max__ = 2;
        for (size_t j_1__ = 0; j_1__ < theta_firing_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_firing" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lograte_firing";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_decay_j_1_max__ = 3;
        for (size_t j_1__ = 0; j_1__ < theta_decay_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_decay" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "logitrate_decay";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "period";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "Q0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "dQ";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "rate_firing";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "rate_decay";
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
        size_t viterbi_k_0_max__ = (N - 1);
        for (size_t k_0__ = 0; k_0__ < viterbi_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "viterbi" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t trend_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < trend_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "trend" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "log_p_state";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Q1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "S1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Q2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "S2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "amp";
        param_names__.push_back(param_name_stream__.str());
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t eta_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lsigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lperiod";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "lQ0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "ldQ";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "f";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_quiet_j_1_max__ = (2 - 1);
        for (size_t j_1__ = 0; j_1__ < theta_quiet_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_quiet" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_quiet";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2_noise";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_firing_j_1_max__ = (2 - 1);
        for (size_t j_1__ = 0; j_1__ < theta_firing_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_firing" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "lograte_firing";
        param_names__.push_back(param_name_stream__.str());
        size_t theta_decay_j_1_max__ = (3 - 1);
        for (size_t j_1__ = 0; j_1__ < theta_decay_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_decay" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "logitrate_decay";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "period";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "Q0";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "dQ";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "rate_firing";
            param_names__.push_back(param_name_stream__.str());
            param_name_stream__.str(std::string());
            param_name_stream__ << "rate_decay";
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
        size_t viterbi_k_0_max__ = (N - 1);
        for (size_t k_0__ = 0; k_0__ < viterbi_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "viterbi" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t trend_j_1_max__ = N;
        for (size_t j_1__ = 0; j_1__ < trend_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "trend" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "log_p_state";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Q1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "S1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "Q2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "S2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "rho2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "tau2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "amp";
        param_names__.push_back(param_name_stream__.str());
    }

}; // model

}  // namespace

typedef model_CeleriteQFDexN_namespace::model_CeleriteQFDexN stan_model;

#ifndef USING_R

stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


#endif
